In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X
list(y)

[0, 1, 2, 3, 4]

In [2]:
X_train, X_test = train_test_split(X, test_size=0.33, random_state=42)

In [3]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [4]:
X_test

array([[2, 3],
       [8, 9]])

In [5]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])